name: Generate keystore
on: workflow_dispatch
jobs:
  gen:
    runs-on: ubuntu-latest
    steps:
      - name: Generate keystore
        run: |
          keytool -genkeypair -v \
            -keystore keystore.jks \
            -keyalg RSA -keysize 2048 -validity 10000 \
            -alias simple_live \
            -storepass SimpleLive2026 -keypass SimpleLive2026 \
            -dname "CN=Simple Live, O=Personal, C=CN"
          base64 -w 0 keystore.jks > keystore_base64.txt
      - uses: actions/upload-artifact@v4
        with:
          name: android-keystore
          path: |
            keystore.jks
            keystore_base64.txt
